services:
  shopping-list:
    container_name: shopping-list-notifications
    build:
      context: ..
      dockerfile: notifications/Dockerfile
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    environment:
      ENV: production
      DATA_DIR: /app/data
      BUCKET: notifications
      DB: notifications.db
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    external: true
