services:
  shopping-list:
    container_name: shopping-list-category-model
    build:
      context: ..
      dockerfile: category-model/Dockerfile
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    environment:
      ENV: production
      DATA_DIR: /app/data
      CATEGORIES_FILE: categories.csv
      MODEL_FILE: model.pkl
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    external: true
