services:
  shopping-list:
    container_name: shopping-list-storage
    image: ghcr.io/bryanvanwinnendael/shopping-list-storage:${IMAGE_TAG:-latest}
    ports:
      - "8010:3000"
    volumes:
      - ./storage:/app/storage
    environment:
      ENV: production
      STORAGE_DIR: ./storage
      PORT: 3000
      LOGS_API_URL: http://shopping-list-logs:3000/api/logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    external: true
