services:
  shopping-list:
    container_name: shopping-list-cron
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      ENV: production
      GOOGLE_APPLICATION_CREDENTIALS: /serviceAccountKey.json
      DATA_DIR: /app/data
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/serviceAccountKey.json:ro
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    name: shopping-list-network
