services:
  shopping-list:
    container_name: shopping-list-cron
    image: ghcr.io/bryanvanwinnendael/shopping-list-cron:${IMAGE_TAG:-latest}
    expose:
      - "3000"
    volumes:
      - ./serviceAccountKey.json:/serviceAccountKey.json:ro
      - ./data:/app/data
    environment:
      ENV: production
      GOOGLE_APPLICATION_CREDENTIALS: /serviceAccountKey.json
      DATA_DIR: /app/data
      BUCKET: cron
      DB: cron.db
      CRON_TIME: "0 0 * * 5"
      CRON_TIME_REMINDER: "0 0 * * 3"
      PORT: 3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    external: true
