name: Build App

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  deploy:
    if: contains(join(github.event.commits.*.message, ' '), 'BUILD')
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy App
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          cd ~/projects/shopping-list/app
          git fetch origin main
          git reset --hard origin/main
          yarn install
          EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} yarn release
          EOF
