name: Products Search µS

on:
  push:
    branches:
      - main
    paths:
      - "services/products-search/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microservice.yml
    with:
      service: products-search