name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/shopping-list-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/projects/shopping-list/server
          git fetch origin main
          git reset --hard origin/main
          docker compose build
          docker compose up -d
          docker image prune -af
          EOF
