name: API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "services/api-gateway/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microservice.yml
    with:
      service: api-gateway