services:
  shopping-list:
    container_name: shopping-list-recipes
    image: ghcr.io/bryanvanwinnendael/shopping-list-recipes:${IMAGE_TAG:-latest}
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    environment:
      ENV: production
      DATA_DIR: /app/data
      BUCKET: recipes
      DB: recipes.db
      PORT: 3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shopping-list-network
networks:
  shopping-list-network:
    external: true
